# Generated by Django 4.1 on 2022-09-02 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата добавления"
            ),
        ),
    ]
